In [37]:
import requests as re
import pandas as pd
import numpy as np
import json
from pandas.io.json import json_normalize
from flatten_json import flatten

In [99]:
class football_flatten:
    
    def __init__(self):
        
        self.page = None
        self.data = None
        self.n = None
        self.d1= None
        self.d2= None
        self.d3= None
   
    def load1(self,page):
        self.page=page
        f=open(f'page{page}.json')
        d=json.load(f)
        return d
        
    def process(data,n):
        
        #self.data=data
        #self.n=n
        data=data['response']
        y=[]
        for dictionary in data:
            y.append(flatten(dictionary))
        data1=json_normalize(y)
        data2=pd.DataFrame()
        data2=data1[['player_name','player_age','player_nationality',f'statistics_{n}_league_name',f'statistics_{n}_league_season',f'statistics_{n}_games_minutes',f'statistics_{n}_games_position',f'statistics_{n}_games_rating',f'statistics_{n}_goals_total',f'statistics_{n}_goals_assists',f'statistics_{n}_goals_saves',f'statistics_{n}_goals_conceded',f'statistics_{n}_passes_key',f'statistics_{n}_passes_accuracy',f'statistics_{n}_tackles_total',f'statistics_{n}_tackles_interceptions',f'statistics_{n}_duels_total',f'statistics_{n}_duels_won',f'statistics_{n}_dribbles_attempts',f'statistics_{n}_dribbles_success',f'statistics_{n}_penalty_scored',f'statistics_{n}_penalty_missed',f'statistics_{n}_penalty_saved']]
        data2=data2.rename(columns={'player_name':'Name','player_age':'Age','player_nationality':'Nationality',f'statistics_{n}_league_name':'League',f'statistics_{n}_league_season':'Season',f'statistics_{n}_games_minutes':'Minutes Played',f'statistics_{n}_games_position':'Position',f'statistics_{n}_games_rating':'Rating',f'statistics_{n}_goals_total':'Goals Scored',f'statistics_{n}_goals_assists':'Assists',f'statistics_{n}_goals_saves':'Goal Saves',f'statistics_{n}_goals_conceded':'Goals Conceded',f'statistics_{n}_passes_key':'Key Passes',f'statistics_{n}_passes_accuracy':'Pass Accuracy',f'statistics_{n}_tackles_total':'Total Tackles',f'statistics_{n}_tackles_interceptions':'Interceptions',f'statistics_{n}_duels_total':'Duels Attempted',f'statistics_{n}_duels_won':'Duels Won',f'statistics_{n}_dribbles_attempts':'Dribble Attempts',f'statistics_{n}_dribbles_success':'Successful Dribbles',f'statistics_{n}_penalty_scored':'Penalties Scored',f'statistics_{n}_penalty_missed':'Penalties Missed',f'statistics_{n}_penalty_saved':'Penalties Saved'})
        return data2
    
    def concat(d1,d2,d3):
        
        Data = pd.concat([d1,d2,d3], axis=0, join='inner',ignore_index=True)
        return Data

In [39]:
p1=football_flatten()
data1=p1.load1(1)

In [42]:
data2=p1.load1(2)
data3=p1.load1(3)

In [92]:
d1=football_flatten.process(data1,0)

<ipython-input-91-dcbe3dee0c65>:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  data1=json_normalize(y)

In [95]:
d2=football_flatten.process(data2,0)
d3=football_flatten.process(data3,0)

<ipython-input-91-dcbe3dee0c65>:23: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  data1=json_normalize(y)

In [100]:
PL_data=football_flatten.concat(d1,d2,d3)
len(PL_data)

57

In [103]:
d11=football_flatten.process(data1,1)
d12=football_flatten.process(data2,1)
d13=football_flatten.process(data3,1)

<ipython-input-99-77dea20f8dc8>:26: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  data1=json_normalize(y)

In [104]:
League_cup=football_flatten.concat(d11,d12,d13)
League_cup.head()

,Name,Age,Nationality,League,Season,Minutes Played,Position,Rating,Goals Scored,Assists,...,Pass Accuracy,Total Tackles,Interceptions,Duels Attempted,Duels Won,Dribble Attempts,Successful Dribbles,Penalties Scored,Penalties Missed,Penalties Saved
0,D. van de Beek,25,Netherlands,League Cup,2021,90.0,Midfielder,6.200000,0.0,NaN,...,53.0,2.0,1.0,12.0,3.0,4.0,1.0,0.0,0.0,NaN
1,R. Varane,29,France,League Cup,2021,0.0,Defender,None,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,David de Gea Quintana,32,Spain,League Cup,2021,0.0,Goalkeeper,None,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Lee Grant,39,England,League Cup,2021,0.0,Goalkeeper,None,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E. Bailly,28,Côte d'Ivoire,League Cup,2021,90.0,Defender,7.700000,0.0,NaN,...,68.0,5.0,NaN,19.0,13.0,NaN,NaN,0.0,0.0,NaN

In [105]:
d21=football_flatten.process(data1,2)
d22=football_flatten.process(data2,2)
d23=football_flatten.process(data3,2)

<ipython-input-99-77dea20f8dc8>:26: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  data1=json_normalize(y)

In [106]:
FAcup_data=football_flatten.concat(d21,d22,d23)
FAcup_data.head()

,Name,Age,Nationality,League,Season,Minutes Played,Position,Rating,Goals Scored,Assists,...,Pass Accuracy,Total Tackles,Interceptions,Duels Attempted,Duels Won,Dribble Attempts,Successful Dribbles,Penalties Scored,Penalties Missed,Penalties Saved
0,D. van de Beek,25,Netherlands,FA Cup,2021.0,18.0,Midfielder,6.900000,0.0,NaN,...,6.0,1.0,NaN,4.0,3.0,NaN,NaN,0.0,0.0,NaN
1,R. Varane,29,France,FA Cup,2021.0,180.0,Defender,7.250000,0.0,NaN,...,59.0,2.0,5.0,12.0,10.0,1.0,1.0,0.0,0.0,NaN
2,David de Gea Quintana,32,Spain,FA Cup,2021.0,90.0,Goalkeeper,7.900000,0.0,NaN,...,19.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3,Lee Grant,39,England,FA Cup,2021.0,0.0,Goalkeeper,None,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
4,E. Bailly,28,Côte d'Ivoire,FA Cup,2021.0,0.0,Defender,None,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
d31=football_flatten.process(data1,3)
d32=football_flatten.process(data2,3)
d33=football_flatten.process(data3,3)

<ipython-input-99-77dea20f8dc8>:26: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  data1=json_normalize(y)

In [110]:
UCL_data=football_flatten.concat(d31,d32,d33)
UCL_data.head()

,Name,Age,Nationality,League,Season,Minutes Played,Position,Rating,Goals Scored,Assists,...,Pass Accuracy,Total Tackles,Interceptions,Duels Attempted,Duels Won,Dribble Attempts,Successful Dribbles,Penalties Scored,Penalties Missed,Penalties Saved
0,D. van de Beek,25,Netherlands,UEFA Champions League,2021,205.0,Midfielder,6.775000,0.0,NaN,...,25.0,8.0,5.0,25.0,14.0,4.0,3.0,0.0,0.0,NaN
1,R. Varane,29,France,UEFA Champions League,2021,352.0,Defender,6.900000,0.0,NaN,...,45.0,3.0,5.0,24.0,17.0,1.0,1.0,0.0,0.0,NaN
2,David de Gea Quintana,32,Spain,UEFA Champions League,2021,630.0,Goalkeeper,6.728571,0.0,NaN,...,15.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3,Lee Grant,39,England,UEFA Champions League,2021,0.0,Goalkeeper,None,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E. Bailly,28,Côte d'Ivoire,UEFA Champions League,2021,180.0,Defender,7.200000,0.0,NaN,...,48.0,3.0,5.0,14.0,8.0,1.0,1.0,0.0,0.0,NaN

In [111]:
PL_data.to_csv('PL_MANU.csv')
League_cup.to_csv('Leaguecup_MU.csv')
FAcup_data.to_csv('FACUP_MU.csv')
UCL_data.to_csv('UCL_MU.csv')